# Generated by Django 2.2.6 on 2019-10-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo')),
                ('descricao', models.TextField()),
                ('imagem_destaque', models.CharField(max_length=500, verbose_name='URL da Imagem de Destaque da rota')),
            ],
        ),
    ]
