# Generated by Django 2.2.6 on 2019-10-04 03:19

from django.db import migrations, models
import rotas.models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0002_auto_20191004_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivoimagem',
            name='arquivo',
            field=models.FileField(upload_to=rotas.models.diretorio_imagens_destino),
        ),
    ]
