# Generated by Django 2.2.6 on 2019-10-04 03:25

from django.db import migrations, models
import django.db.models.deletion
import rotas.models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0003_auto_20191004_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivoimagem',
            name='arquivo',
            field=models.FileField(upload_to=rotas.models.diretorio_imagens_destino),
        ),
        migrations.CreateModel(
            name='DestinoDeRota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rotas.Destino')),
                ('rota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rotas.Rota')),
            ],
        ),
        migrations.AddField(
            model_name='rota',
            name='destinos',
            field=models.ManyToManyField(through='rotas.DestinoDeRota', to='rotas.Destino', verbose_name=''),
        ),
    ]
