# Generated by Django 2.2.6 on 2019-10-04 03:31

from django.db import migrations, models
import rotas.models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0004_auto_20191004_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinoderota',
            options={'ordering': ['ordem']},
        ),
        migrations.AddField(
            model_name='destinoderota',
            name='ordem',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='arquivoimagem',
            name='arquivo',
            field=models.FileField(upload_to=rotas.models.diretorio_imagens_destino),
        ),
    ]
