# Generated by Django 2.2.6 on 2019-10-04 03:35

from django.db import migrations, models
import rotas.models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0005_auto_20191004_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='tipo',
            field=models.CharField(choices=[('atracao', 'Atração'), ('hospedagem', 'Hotel'), ('restaurante', 'Restaurante'), ('evento', 'Evento')], default='atracao', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arquivoimagem',
            name='arquivo',
            field=models.FileField(upload_to=rotas.models.diretorio_imagens_destino),
        ),
    ]
