# Generated by Django 2.2.6 on 2019-10-05 09:18

from django.db import migrations, models
import django.db.models.deletion
import rotas.models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0007_auto_20191004_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome Tag')),
            ],
        ),
        migrations.AddField(
            model_name='rota',
            name='distancia',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='imagem',
            field=models.CharField(max_length=250, null=True, verbose_name='Caminho da imagem'),
        ),
        migrations.AddField(
            model_name='rota',
            name='pontos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rota',
            name='valor',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='arquivoimagem',
            name='arquivo',
            field=models.FileField(upload_to=rotas.models.diretorio_imagens_destino),
        ),
        migrations.CreateModel(
            name='TagsRota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rotas.Rota')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rotas.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='rota',
            name='tags',
            field=models.ManyToManyField(through='rotas.TagsRota', to='rotas.Tag'),
        ),
    ]
