# Generated by Django 2.2.6 on 2019-10-05 10:24

from django.db import migrations, models
import rotas.models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0008_auto_20191005_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='tempo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='arquivoimagem',
            name='arquivo',
            field=models.FileField(upload_to=rotas.models.diretorio_imagens_destino),
        ),
    ]
