# Generated by Django 2.2.6 on 2019-10-05 11:02

from django.db import migrations, models
import rotas.models


class Migration(migrations.Migration):

    dependencies = [
        ('rotas', '0010_auto_20191005_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivoimagem',
            name='arquivo',
            field=models.FileField(upload_to=rotas.models.diretorio_imagens_destino),
        ),
    ]
